name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # প্রতিদিন একবার
  workflow_dispatch:     # manually run করার জন্য

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: faysalmahamudhimel
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push generated files to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: output
